version: '3.1'
services:
  datareade-dev:
    image: dottjt/datareade
    container_name: 'datareade-dev'
    build:
      context: ../../../
      dockerfile: ./deployment/docker/dev/Dockerfile
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 120s
    ports:
      - 7777:7777
    env_file:
      - ../../environment/.env
